Issue #176: Copy "resources" folder in toolkit:build-dist.
ec-europa/ssk pull request #177
Opened 2019-07-25 16:53 UTC by vever001

See https://github.com/ec-europa/toolkit/issues/176
This allows, among other things, use of local patches in composer.json.

2019-07-25 17:18 UTC, vever001 commented
Tests from release/4.x branch seem broken.
Similar to https://github.com/openeuropa/task-runner/pull/102/commits/e1376e74836fb14e7535ee4efbf2eca030673e92 I think ec-europa/qa-automation needs to update `"openeuropa/code-review: "^1.0@beta",`

2019-07-26 07:45 UTC, jonhy81 requested changes
Hi @vever001 , it looks good but it need some clean up after. Can you remove the cloned resources folder after, if not it will be pushed into docker image.

2019-07-26 13:57 UTC, vever001 commented
Something like this?
A symlink is probably better if we're not going to include it in the final dist I suppose.

2019-08-01 06:47 UTC, verbruggenalex commented
I want to propose an alternate solution to this. Instead of grabbing the individual parts needed for a composer install --no-dev. Why not grab "everything" in a tmp folder and run it there. This will allow us to:
- apply patches
- symlink local modules
- etc

After we created the tmp/dist/prep for example we can rsync what we need to the actual dist folder...

What do you think about this approach @vever001

2019-08-01 10:10 UTC, vever001 commented
Sounds good but it will copy everything which may not be strictly necessary.
I wonder if we couldn't make a very small composer-plugin that would allow us to pass a `--destination-folder` option to composer install/update.

2019-08-01 11:36 UTC, verbruggenalex commented
I think it's a small price to pay (copy all) to have everything working as expected. Building a plugin would mean taking into account every path change of patches, custom modules, scripts, maybe even more.

I'll make a pull request tomorrow and have you guys take a look at it.

2019-08-01 17:02 UTC, vever001 commented
@verbruggenalex I had some fun with composer and made a small POC that **may** be an alternative: https://github.com/vever001/composer-installers-dir

Simply follow the commands from the readme and you should have the `dist`folder built.
It's not perfect, but it's a possibility.

2019-08-07 08:56 UTC, verbruggenalex commented
Hi @vever001 , I think I'm going to go with the tmp dir solution (https://github.com/ec-europa/toolkit/pull/188). This because after you run "composer install --no-dev" with local "path" packages defined you still have symlinks in the dist folder.

So there's actually a need for rsync to happen to get the local "path" packages resolved correctly.

But thank you for your proposal, I didn't realize the plugin for this would be so small.

2019-08-07 08:56 UTC, closed without merging

2019-08-19 12:12 UTC, vever001 commented
Hi @verbruggenalex 
Sry I was on holidays so I just see your message now.

I think the amount of repos using path packages are very limited, but it is indeed a valid concern.
What would be possible is to create a new command: e.g `composer build --dest-dir=...` that would apply the changes to the composer config on the fly.
And would force all "path" packages to use the mirorring/copy method.
If you're interested let me know. If not, no worries.