DQA-3914: Component-check better message.
ec-europa/ssk pull request #519
Opened 2022-05-18 14:38 UTC by joaocsilva

2022-05-19 12:57 UTC, jonhy81 requested changes

2022-05-19 12:57 UTC, jonhy81 commented on src/TaskRunner/Commands/ToolCommands.php
> +                    $this->say("The use of $packageName:$packageVersion is restricted. Contact QA Team.");
```suggestion
                    $this->say("The use of $packageName:$packageVersion is " . $modules[$packageName]['status'] . ". Contact QA Team.");
```

2022-05-19 12:58 UTC, joaocsilva commented on src/TaskRunner/Commands/ToolCommands.php
> +                    $this->say("Package $packageName:$packageVersion authorized.");
```suggestion
```

2022-05-20 07:08 UTC, jonhy81 approved these changes

2022-05-20 07:08 UTC, merged