DQA-6074: Create .gitattributes file for toolkit.
ec-europa/ssk pull request #630
Opened 2023-02-06 16:00 UTC by zarabatana

2023-02-07 08:07 UTC, joaocsilva requested changes
Hi @zarabatana , 
I'm suggesting some more files to be added and fixing a typo in the phpunit.xml.dist file.
The rest is just alignment

2023-02-07 08:07 UTC, joaocsilva commented on .gitattributes
> +.gitattributes     export-ignore
I think we can exclude some more files, what do you think?
```suggestion
.drone.yml         export-ignore
.editorconfig      export-ignore
.eslintrc.json     export-ignore
.gitattributes     export-ignore
```

2023-02-07 08:07 UTC, joaocsilva commented on .gitattributes
> +phpunit.xml.dist.  export-ignore
Typo
```suggestion
phpunit.xml.dist   export-ignore
```

2023-02-07 08:07 UTC, joaocsilva commented on .gitattributes
> +*.zsh      text eol=lf
```suggestion
*.fish            text eol=lf
*.zsh             text eol=lf
```

2023-02-07 08:07 UTC, joaocsilva commented on .gitattributes
> +*.patch    -text
```suggestion
*.patch           -text
```

2023-02-15 13:13 UTC, jonhy81 approved these changes

2023-02-15 13:14 UTC, joaocsilva approved these changes

2023-02-15 13:14 UTC, merged