DQA-10386: Remove package version parameter of the endpoint.
ec-europa/ssk pull request #792
Opened 2024-11-07 09:35 UTC by LuisSantosEncinas

2024-11-07 09:54 UTC, crgomes approved these changes, later dismissed

2024-11-07 16:29 UTC, joaocsilva requested changes
Hi @LuisSantosEncinas ,
Lets use the version 0.0.17 for the moment

2024-11-07 16:29 UTC, joaocsilva commented on src/Mock.php
> +    private static string $defaultTag = '0.0.18';
```suggestion
    private static string $defaultTag = '0.0.17';
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/component-check.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/project/ec-europa/toolkit/information.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/project/ec-europa/toolkit/information.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/component-check.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/toolkit-requirements.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/toolkit-requirements.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/component-check.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/package-reviews.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/package-reviews.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/component-check.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/project/ec-europa/toolkit/information.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/project/ec-europa/toolkit/information.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/component-check.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/toolkit-requirements.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/toolkit-requirements.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/component-check.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/package-reviews.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/package-reviews.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/component-check.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/package-reviews.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/package-reviews.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/notifications.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/notifications.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/notifications.json
```

2024-11-07 16:29 UTC, joaocsilva commented on tests/fixtures/commands/notifications.yml
> +    - file: .toolkit-mock/0.0.18/api/v1/notifications.json
```suggestion
    - file: .toolkit-mock/0.0.17/api/v1/notifications.json
```

2024-11-12 09:26 UTC, jonhy81 approved these changes

2024-11-12 09:37 UTC, joaocsilva approved these changes

2024-11-12 09:51 UTC, merged